###
### get measurements
GET {{carbonlog-host}}/carbon-logs/measurements
Authorization: Basic {{static-auth-token}}
###
GET {{carbonlog-host}}

### add measurement
POST {{carbonlog-host}}/carbon-logs/measurements/3.6
Authorization: Basic {{static-auth-token}}

