###
### get measurements
GET {{carbonlog-host}}/carbon-logs/measurements
Authorization: Bearer {{static-auth-token}}

###
GET {{carbonlog-host}}/healthz

### add measurement
POST {{carbonlog-host}}/carbon-logs/measurements/3.6
Authorization: Bearer {{static-auth-token}}

### add measurement
POST {{carbonlog-host}}/carbon-logs/measurements
Content-Type: application/json
Authorization: Bearer {{static-auth-token}}

{
  "id": "test-update-measurement-id",
  "co2Kg": 42,
  "dt": "2022-11-27T11:00:01.759Z",
  "inputDescription": "kurwa"
}


### update measurement
PUT {{carbonlog-host}}/carbon-logs/measurements/test-update-measurement-id
Content-Type: application/json
Authorization: Bearer {{static-auth-token}}

{
  "co2Kg": 6.66,
  "dt": "2023-11-27T11:00:01.759Z",
  "inputDescription": "kurwa updated"
}
