/*
 * This file was generated by the Gradle 'init' task.
 */


val springCoreVersion: String  = "7.0.0"
val springBootVersion: String = "4.0.0"

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.springframework:spring-context:$springCoreVersion")
        implementation("org.springframework:spring-test:$springCoreVersion")
        implementation("org.springframework.boot:spring-boot-starter-webflux:$springBootVersion")
        implementation("org.springframework.boot:spring-boot-starter-actuator:$springBootVersion")
        implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.20.1")
        implementation("io.projectreactor.kotlin:reactor-kotlin-extensions:1.3.0")
        testImplementation("org.springframework.boot:spring-boot-starter-test:$springBootVersion")
        implementation("org.springframework.boot:spring-boot-starter-logging:$springBootVersion")
        testImplementation("io.projectreactor:reactor-test:3.8.1")
        testImplementation("org.springframework.security:spring-security-test:$springCoreVersion")

        implementation("org.mongodb:mongodb-driver-reactivestreams:5.6.2")

        testImplementation("org.assertj:assertj-core:3.27.6")
    }

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.12.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    testImplementation("org.assertj:assertj-core")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
