/*
 * This file was generated by the Gradle 'init' task.
 */


val springCoreVersion: String  = "7.0.3"
val springBootVersion: String = "4.0.1"

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.springframework:spring-context:$springCoreVersion")
        testImplementation("org.springframework:spring-test:$springCoreVersion")
        testImplementation("org.springframework.security:spring-security-test:$springCoreVersion")

        implementation("org.springframework.boot:spring-boot-starter-webflux:$springBootVersion")
        implementation("org.springframework.boot:spring-boot-starter-actuator:$springBootVersion")
        implementation("org.springframework.boot:spring-boot-starter-security:${springBootVersion}")
        testImplementation("org.springframework.boot:spring-boot-starter-test:$springBootVersion")
        testImplementation("org.springframework.boot:spring-boot-webtestclient:${springBootVersion}")

        implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.21.0")
        implementation("io.projectreactor.kotlin:reactor-kotlin-extensions:1.3.0")
        implementation("tools.jackson.module:jackson-module-kotlin:3.0.4")
        implementation("org.mongodb:mongodb-driver-reactivestreams:5.6.2")
        testImplementation("io.projectreactor:reactor-test:3.8.2")
        testImplementation("org.testcontainers:junit-jupiter:1.21.4")
        testImplementation("org.assertj:assertj-core:3.27.6")
        testImplementation("net.javacrumbs.json-unit:json-unit-assertj:5.1.0")
    }

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:6.0.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    testImplementation("org.assertj:assertj-core")
    testImplementation("net.javacrumbs.json-unit:json-unit-assertj")

    testImplementation("org.testcontainers:junit-jupiter")
    testImplementation ("org.springframework:spring-test")
    testImplementation("io.projectreactor:reactor-test")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
